let data=[{"name":"RajeshKumar",
            "batch":"B45WD",
            "gender":"Male",
            "qualification":"BSC",
            "id":"0"},
            {"name":"Anitha",
            "batch":"B45WD",
            "gender":"Female",
            "qualification":"B.Com",
            "id":"1"},
            {"name":"Prabhu",
            "batch":"B45WD",
            "gender":"Male",
            "qualification":"BSC",
            "id":"2"},
            {"name":"Soosana",
            "batch":"B45WD",
            "gender":"Female",
            "qualification":"BBA",
            "id":"3"},
            {"name":"Raghul",
            "batch":"B45WD",
            "gender":"Male",
            "qualification":"BCA",
            "id":"4"},
            {"name":"Vishnu",
            "batch":"B45WD",
            "gender":"Male",
            "qualification":"BBA",
            "id":"5"},
            {"name":"Porko",
            "batch":"B45WD",
            "gender":"Male",
            "qualification":"B.Tech",
            "id":"6"}]
            
export default data;